### ISSUE TITLE
Angular 17 - I am unable to run on angular 17.2

### ISSUE THREAD

**Issue by fordsworth** [ngxpert/cmdk#1]
##  I am getting an error when running this on 17.2

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[*] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
When I install on a project running angular 17.2 I get the following error 

Error: node_modules/@ngxpert/cmdk/lib/cmdk.module.d.ts:17:97 - error TS2339: Property 'DynamicViewModule' does not exist on type 'typeof import("@ngneat/overview")'.

17     static ɵmod: i0.ɵɵNgModuleDeclaration<CmdkModule, never, [typeof i1.CommonModule, typeof i2.DynamicViewModule, typeof i3.A11yModule, typeof i4.CommandComponent, typeof i5.InputDirective, typeof i6.EmptyDirective, typeof i7.GroupComponent, typeof i8.SeparatorComponent, typeof i9.ItemDirective, typeof i10.LoaderDirective, typeof i11.ListComponent], [typeof i4.CommandComponent, typeof i5.InputDirective, typeof i6.EmptyDirective, typeof i7.GroupComponent, typeof i8.SeparatorComponent, typeof i9.ItemDirective, typeof i10.LoaderDirective, typeof i11.ListComponent]>;

## Expected behavior

install using ng add @ngxpert/cmdk
ng serve the application should start 
## Environment
mac os 
<pre><code>
Angular version: X.Y.Z

Browser:
- [*] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v20.10.0v 
- Platform: Mac

Others:

</code></pre>

**Comment by kiesman99** [comment]
Had the same issue, because my `ng add` failed.

For me it fixed after following the [installation guide](https://github.com/ngxpert/cmdk?tab=readme-ov-file#npm)

**Comment by fordsworth** [comment]
@kiesman99 your suggestion worked

**Comment by fordsworth** [comment]
Following the latest installation guide fixed the problem 

[installation guide](https://github.com/ngxpert/cmdk?tab=readme-ov-file#npm)
